"""
Tensor math library
"""
from __future__ import annotations
import collections.abc
import typing
__all__: list[str] = ['Matrix', 'Scalar', 'Vector']
class Matrix:
    @typing.overload
    def __add__(self, arg0: Matrix) -> Matrix:
        ...
    @typing.overload
    def __add__(self, arg0: typing.SupportsFloat) -> Matrix:
        ...
    @typing.overload
    def __getitem__(self, arg0: typing.SupportsInt) -> float:
        ...
    @typing.overload
    def __getitem__(self, arg0: tuple) -> float:
        ...
    @typing.overload
    def __iadd__(self, arg0: Matrix) -> Matrix:
        ...
    @typing.overload
    def __iadd__(self, arg0: typing.SupportsFloat) -> Matrix:
        ...
    @typing.overload
    def __imul__(self, arg0: Matrix) -> Matrix:
        ...
    @typing.overload
    def __imul__(self, arg0: typing.SupportsFloat) -> Matrix:
        ...
    @typing.overload
    def __init__(self, arg0: typing.Annotated[collections.abc.Sequence[typing.SupportsInt], "FixedSize(2)"]) -> None:
        ...
    @typing.overload
    def __init__(self, arg0: typing.Annotated[collections.abc.Sequence[typing.SupportsInt], "FixedSize(2)"], arg1: typing.SupportsFloat) -> None:
        ...
    @typing.overload
    def __init__(self, arg0: typing.Annotated[collections.abc.Sequence[typing.SupportsInt], "FixedSize(2)"], arg1: collections.abc.Sequence[typing.SupportsFloat]) -> None:
        ...
    @typing.overload
    def __init__(self, arg0: typing.Annotated[collections.abc.Sequence[typing.SupportsInt], "FixedSize(2)"], arg1: typing.SupportsFloat, arg2: typing.SupportsFloat) -> None:
        ...
    @typing.overload
    def __isub__(self, arg0: Matrix) -> Matrix:
        ...
    @typing.overload
    def __isub__(self, arg0: typing.SupportsFloat) -> Matrix:
        ...
    def __itruediv__(self, arg0: typing.SupportsFloat) -> Matrix:
        ...
    def __matmul__(self, arg0: Matrix) -> Matrix:
        ...
    @typing.overload
    def __mul__(self, arg0: Matrix) -> Matrix:
        ...
    @typing.overload
    def __mul__(self, arg0: typing.SupportsFloat) -> Matrix:
        ...
    def __neg__(self) -> Matrix:
        ...
    def __pos__(self) -> Matrix:
        ...
    def __radd__(self, arg0: typing.SupportsFloat) -> Matrix:
        ...
    def __repr__(self) -> str:
        ...
    def __rmul__(self, arg0: typing.SupportsFloat) -> Matrix:
        ...
    def __rsub__(self, arg0: typing.SupportsFloat) -> Matrix:
        ...
    @typing.overload
    def __setitem__(self, arg0: typing.SupportsInt, arg1: typing.SupportsFloat) -> None:
        ...
    @typing.overload
    def __setitem__(self, arg0: tuple, arg1: typing.SupportsFloat) -> None:
        ...
    @typing.overload
    def __sub__(self, arg0: Matrix) -> Matrix:
        ...
    @typing.overload
    def __sub__(self, arg0: typing.SupportsFloat) -> Matrix:
        ...
    def __truediv__(self, arg0: typing.SupportsFloat) -> Matrix:
        ...
    def get_axes(self) -> typing.Annotated[list[int], "FixedSize(2)"]:
        ...
    def get_shape(self) -> typing.Annotated[list[int], "FixedSize(2)"]:
        ...
    def get_size(self) -> int:
        ...
    def t(self) -> Matrix:
        ...
    @typing.overload
    def transpose(self, arg0: typing.Annotated[collections.abc.Sequence[typing.SupportsInt], "FixedSize(2)"]) -> Matrix:
        ...
    @typing.overload
    def transpose(self, arg0: typing.SupportsInt, arg1: typing.SupportsInt) -> Matrix:
        ...
class Scalar:
    @typing.overload
    def __add__(self, arg0: Scalar) -> Scalar:
        ...
    @typing.overload
    def __add__(self, arg0: typing.SupportsFloat) -> Scalar:
        ...
    @typing.overload
    def __iadd__(self, arg0: Scalar) -> Scalar:
        ...
    @typing.overload
    def __iadd__(self, arg0: typing.SupportsFloat) -> Scalar:
        ...
    @typing.overload
    def __imul__(self, arg0: Scalar) -> Scalar:
        ...
    @typing.overload
    def __imul__(self, arg0: typing.SupportsFloat) -> Scalar:
        ...
    @typing.overload
    def __init__(self, arg0: typing.Annotated[collections.abc.Sequence[typing.SupportsInt], "FixedSize(0)"]) -> None:
        ...
    @typing.overload
    def __init__(self, arg0: typing.Annotated[collections.abc.Sequence[typing.SupportsInt], "FixedSize(0)"], arg1: typing.SupportsFloat) -> None:
        ...
    @typing.overload
    def __init__(self, arg0: typing.Annotated[collections.abc.Sequence[typing.SupportsInt], "FixedSize(0)"], arg1: collections.abc.Sequence[typing.SupportsFloat]) -> None:
        ...
    @typing.overload
    def __init__(self, arg0: typing.Annotated[collections.abc.Sequence[typing.SupportsInt], "FixedSize(0)"], arg1: typing.SupportsFloat, arg2: typing.SupportsFloat) -> None:
        ...
    @typing.overload
    def __isub__(self, arg0: Scalar) -> Scalar:
        ...
    @typing.overload
    def __isub__(self, arg0: typing.SupportsFloat) -> Scalar:
        ...
    def __itruediv__(self, arg0: typing.SupportsFloat) -> Scalar:
        ...
    @typing.overload
    def __mul__(self, arg0: Scalar) -> Scalar:
        ...
    @typing.overload
    def __mul__(self, arg0: typing.SupportsFloat) -> Scalar:
        ...
    def __neg__(self) -> Scalar:
        ...
    def __pos__(self) -> Scalar:
        ...
    def __radd__(self, arg0: typing.SupportsFloat) -> Scalar:
        ...
    def __repr__(self) -> str:
        ...
    def __rmul__(self, arg0: typing.SupportsFloat) -> Scalar:
        ...
    def __rsub__(self, arg0: typing.SupportsFloat) -> Scalar:
        ...
    @typing.overload
    def __sub__(self, arg0: Scalar) -> Scalar:
        ...
    @typing.overload
    def __sub__(self, arg0: typing.SupportsFloat) -> Scalar:
        ...
    def __truediv__(self, arg0: typing.SupportsFloat) -> Scalar:
        ...
    def get_axes(self) -> typing.Annotated[list[int], "FixedSize(0)"]:
        ...
    def get_shape(self) -> typing.Annotated[list[int], "FixedSize(0)"]:
        ...
    def get_size(self) -> int:
        ...
class Vector:
    @typing.overload
    def __add__(self, arg0: Vector) -> Vector:
        ...
    @typing.overload
    def __add__(self, arg0: typing.SupportsFloat) -> Vector:
        ...
    @typing.overload
    def __getitem__(self, arg0: typing.SupportsInt) -> float:
        ...
    @typing.overload
    def __getitem__(self, arg0: tuple) -> float:
        ...
    @typing.overload
    def __iadd__(self, arg0: Vector) -> Vector:
        ...
    @typing.overload
    def __iadd__(self, arg0: typing.SupportsFloat) -> Vector:
        ...
    @typing.overload
    def __imul__(self, arg0: Vector) -> Vector:
        ...
    @typing.overload
    def __imul__(self, arg0: typing.SupportsFloat) -> Vector:
        ...
    @typing.overload
    def __init__(self, arg0: typing.Annotated[collections.abc.Sequence[typing.SupportsInt], "FixedSize(1)"]) -> None:
        ...
    @typing.overload
    def __init__(self, arg0: typing.Annotated[collections.abc.Sequence[typing.SupportsInt], "FixedSize(1)"], arg1: typing.SupportsFloat) -> None:
        ...
    @typing.overload
    def __init__(self, arg0: typing.Annotated[collections.abc.Sequence[typing.SupportsInt], "FixedSize(1)"], arg1: collections.abc.Sequence[typing.SupportsFloat]) -> None:
        ...
    @typing.overload
    def __init__(self, arg0: typing.Annotated[collections.abc.Sequence[typing.SupportsInt], "FixedSize(1)"], arg1: typing.SupportsFloat, arg2: typing.SupportsFloat) -> None:
        ...
    @typing.overload
    def __isub__(self, arg0: Vector) -> Vector:
        ...
    @typing.overload
    def __isub__(self, arg0: typing.SupportsFloat) -> Vector:
        ...
    def __itruediv__(self, arg0: typing.SupportsFloat) -> Vector:
        ...
    def __matmul__(self, arg0: Vector) -> Scalar:
        ...
    @typing.overload
    def __mul__(self, arg0: Vector) -> Vector:
        ...
    @typing.overload
    def __mul__(self, arg0: typing.SupportsFloat) -> Vector:
        ...
    def __neg__(self) -> Vector:
        ...
    def __pos__(self) -> Vector:
        ...
    def __radd__(self, arg0: typing.SupportsFloat) -> Vector:
        ...
    def __repr__(self) -> str:
        ...
    def __rmul__(self, arg0: typing.SupportsFloat) -> Vector:
        ...
    def __rsub__(self, arg0: typing.SupportsFloat) -> Vector:
        ...
    @typing.overload
    def __setitem__(self, arg0: typing.SupportsInt, arg1: typing.SupportsFloat) -> None:
        ...
    @typing.overload
    def __setitem__(self, arg0: tuple, arg1: typing.SupportsFloat) -> None:
        ...
    @typing.overload
    def __sub__(self, arg0: Vector) -> Vector:
        ...
    @typing.overload
    def __sub__(self, arg0: typing.SupportsFloat) -> Vector:
        ...
    def __truediv__(self, arg0: typing.SupportsFloat) -> Vector:
        ...
    def get_axes(self) -> typing.Annotated[list[int], "FixedSize(1)"]:
        ...
    def get_shape(self) -> typing.Annotated[list[int], "FixedSize(1)"]:
        ...
    def get_size(self) -> int:
        ...
